### ISSUE TITLE
Allow filtering by attributes/relations on permissions/lookup-entity

### ISSUE THREAD

**Issue by michelkaeser** [Permify/permify#1024]
**Is your feature request related to a problem? Please describe.**
When looking up entities via https://docs.permify.co/docs/api-overview/permission/lookup-entity/ this allows filtering via the subject. In case the result could be huge, it would help if the returned entities can be further limited by providing additional filters on the attributes or relations.

**Describe the solution you'd like**
I imagine passing additional filter parameters should be possible.

**Describe alternatives you've considered**
The streaming API seems to address the large sets already but does so by offering more efficient ways to load them rather than limiting them.

Solving it on the schema level is another option but might not be feasible.

**Additional context**
–

**Comment by michelkaeser** [comment]
#1519 is somewhat related as it also asks for a way to limit the potential hits.

**Comment by firatcand** [comment]
[Related to a Slack conversation](https://permify.unthread.io/dashboard/inbox/all/conversations/fd6c9077-5186-4e00-8df8-9b358b4f8b01)
