### ISSUE TITLE
Adding modeling gif to the docs

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#103]
Adding the modeling gif/video to the "docs/getting-started/modeling" section between the main title and secondary title: "Permify Schema"

**Video:**
![modeling-gif](https://raw.githubusercontent.com/Permify/permify/master/assets/permify-dsl.gif)

**Position of the video that need to be added:**
<img width="857" alt="Screen Shot 2022-12-23 at 14 23 51" src="https://user-images.githubusercontent.com/34595361/209327886-a46af909-0852-4caf-b124-b88db7b5ebfc.png">

**Comment by bhagatpratham** [comment]
Hi @EgeAytin, Can I work on this?

**Comment by EgeAytin** [comment]
Hi @bhagatpratham I assigned you, happy hacking 🚀🎉
