### ISSUE TITLE
Support exporting OTLP over gRPC

### ISSUE THREAD

**Issue by jbergstroem** [Permify/permify#1090]
**Is your feature request related to a problem? Please describe.**
The OTLP exporter for tracers, logs and metrics currently are hardcoded to use HTTP. It would be great if it optionally supported gRPC as well:

https://github.com/Permify/permify/blob/c4e26ce817144687671abee51c0d0df3b40736e5/pkg/telemetry/meterexporters/otlp.go#L11-L15

**Describe the solution you'd like**
1. expand the meter/logging/tracing config with a sub object called `oltp` containing `protocol` (if this is the only option that supports gRPC. If supported by multiple libraries I'd keep it at the top level.
2. branch on above option (which defaults to http) and invoke the different exporter.

**Describe alternatives you've considered**
Stick with HTTP

**Comment by mohanish2504** [comment]
Can i attempt

**Comment by tolgaOzen** [comment]
Hello @mohanish2504, I had assigned you, but we've decided to proceed differently. From now on, let anyone /attempt and submit PRs without needing to be assigned and we will reward the best PR.

**Comment by vikashsprem** [comment]
@tolgaOzen, is it still pending?
