### ISSUE TITLE
Permify Fails to Launch with PostgreSQL Without Specific Environment Variables

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#1251]
**Description:**
When running Permify with PostgreSQL, the application fails to properly start if the following environment variables are not set:

PERMIFY_DATABASE_MAX_OPEN_CONNECTIONS=100
PERMIFY_DATABASE_MAX_IDLE_CONNECTIONS=20
PERMIFY_DATABASE_MAX_CONNECTION_LIFETIME=300s
PERMIFY_DATABASE_MAX_CONNECTION_IDLE_TIME=60s

**Suggested Solution:**
To resolve this issue, default values should be added to `internal/config`. This would ensure that the application can start correctly even if these specific environment variables are not explicitly set by the user.

**Impact:**
Without these default settings, users must manually set these environment variables to avoid startup failures, which could lead to operational disruptions and increased setup complexity.

**Next Steps:**
- [ ] Add default values for the above-mentioned environment variables to `internal/config`.
- [ ] Test to ensure that the application starts correctly with and without these environment variables set by the user.

**Comment by thecaffeinedev** [comment]
Hi @tolgaOzen, I have created a draft PR for this. Could you please check it and let me know if I need to make any more changes? Thanks!
