### ISSUE TITLE
[BUG]: Playground crash "System Error: Go program has already exited" while writing schema

### ISSUE THREAD

**Issue by Dogacel** [Permify/permify#1315]
**Describe the bug**
When I am writing a schema, I am occasionally seeing the _"System Error: Go program has already exited"_ error and my playground state becomes broken and this error keeps showing up.

The first exception I see is
> System Error: Cannot read properties of undefined (reading 'length')

And all consecutive exception messages was about exit state. 

**To Reproduce**

1. Go to: https://play.permify.co/?s=rHILiGNAoXSLVJiCof-HO
2. Delete a single `"` and press space.

Final state should look like this:
```
entity user {}

rule x(y string) {
    "  == y   
}


**Expected behavior**
Application should fail softly on syntax errors.

**Comment by Dogacel** [comment]
Here is another reproducable: https://play.permify.co/?s=8QWyP0H81pbUBF1VkJYsV

Just click and it would crash.

**Comment by tolgaOzen** [comment]
Hi @Dogacel , we've resolved these issues in the playground. Could you delete the cache and test it? If it's fixed, could you please close the issue?

**Comment by Dogacel** [comment]
> Hi @Dogacel , we've resolved these issues in the playground. Could you delete the cache and test it? If it's fixed, could you please close the issue?

Yep, can't reproduce now.
