### ISSUE TITLE
[BUG] Missing Validation in Lookup Subject

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#1390]
**Description:**
When the request is structured as shown below, it returns an empty result instead of a validation error:

```json
{
    "metadata": {
        "depth": 30,
        "schema_version": ""
    },
    "entity": {"type": "patient", "id": "x"},
    "permission": "view",
    "subject": "user"
}
```

However, the correct request format is:

```json
{
    "metadata": {
        "depth": 30,
        "schema_version": ""
    },
    "entity": {"type": "patient", "id": "x"},
    "permission": "view",
    "subject_reference": {
        "type": "user",
        "relation": ""
    }
}
```

**Expected Behavior:**
The Permify should return a validation error when the subject field is incorrectly formatted, instead of returning an empty result.

Permify version: v0.10.1

**Comment by rishirishhh** [comment]
Can I pick this task ?

**Comment by 35C4n0r** [comment]
@tolgaOzen can you kindly assign this issue to me.

**Comment by tolgaOzen** [comment]
This issue has been addressed in a pull request (https://github.com/Permify/permify/pull/1405) that was merged, so I'm closing it.
