### ISSUE TITLE
[BUG] `/healthz` Endpoint Requires Authentication with OIDC Enabled

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#1473]
When OIDC is enabled, the `/healthz` endpoint is still requiring bearer authentication. This is causing issues with health checks, as the `/healthz` endpoint should be accessible without any authentication.

#### Expected Behavior
The `/healthz` endpoint should not require authentication when accessed, even with OIDC enabled.

#### Actual Behavior
The `/healthz` endpoint requires bearer authentication, which interferes with health checks.

#### Environment
- **Project Version:** v1.0.1

**Comment by durgakiran** [comment]
thank you

**Comment by tolgaOzen** [comment]
Hi @durgakiran, we've made some improvements related to the issue. Could you please test it using this image `ghcr.io/permify/permify-beta:v1.0.2-2c9db609`? If the problem is resolved, you can close this issue

**Comment by durgakiran** [comment]
working with new beta version. Thank you
