### ISSUE TITLE
[BUG] List scheam curl has read schema endpoint

### ISSUE THREAD

**Issue by durgakiran** [Permify/permify#1492]
**Describe the bug**
In Documentation, [list schema page ](https://docs.permify.co/api-reference/schema/list-schema) curl has  read schema endpoint instead it should have `/v1/tenants/{tenant_id}/schemas/list` endpoint.

**To Reproduce**
1. go to https://docs.permify.co/api-reference/schema/list-schema
2. click on curl tab.

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/449eace5-b7fd-4510-80bd-f893f261e62d">

**Expected behavior**
Should have proper curl.

**Comment by durgakiran** [comment]
Let me know how to run these docs locally, couldn't find where this curl coming from. Happy to contribute.

**Comment by tolgaOzen** [comment]
Hello @durgakiran , To run the documentation, you'll need to execute the `mintlify dev` command in the docs folder. Additionally, the references in the documentation are generated from the proto files located in [this](https://github.com/Permify/permify/blob/master/proto/base/v1/service.proto). If you make any changes there, simply run the `buf generate` command in the root folder to update the generated files.

Let me know if you need any further assistance!
