### ISSUE TITLE
Postman Collection default field error

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#154]
In the write relationships API, the subject ids default value should be [] not [""]
<img width="277" alt="Screen Shot 2023-01-24 at 12 03 57" src="https://user-images.githubusercontent.com/34595361/214396813-5ec3525a-3f96-4f4f-9c65-cc4fe4065228.png">

**Comment by tolgaOzen** [comment]
https://www.postman.com/permify-dev/workspace/permify/collection
