### ISSUE TITLE
Automatic upgrades or base Docker images can lead to supply chain attacks (High)

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#1557]
Find more live information in Aikido here: https://app.aikido.dev/queue?sidebarIssue=2485320&groupId=6798&sidebarIssueTask=50681&sidebarTab=tasks

==== Scope ====
This task includes issues in the following code repository:
- permify: Dockerfile.release

==== TLDR ====
It's recommended to pin the version of base images inside of Docker containers. Using a dynamic version can cause unexpected behavior and at worst, can lead to supply chain attacks. On top of that the 'latest' tag does not always automatically refer to the newest version of the image, so it can also lead to using an outdated version of the base image. 

==== How to fix ====
Pin the base image by changing FROM image:latest to FROM image:3.17.1

**Comment by polarathene** [comment]
I understand why `:latest` is used with the chainguard image (only option for their free tier), digest pinning might be valid though.

~~Any reason you moved away from Google distroless to chainguard as the base btw? I didn't see any context at the PR~~ https://github.com/Permify/permify/pull/358

Oh never mind, [`distroless.dev` was chainguard](https://github.com/distroless):

> Distroless images have moved to the [Chainguard Images](https://github.com/chainguard-images) repo.

> 
> Please update any image references to use the `cgr.dev/chainguard` registry i.e. `docker pull distroless.dev/static` is now `docker pull cgr.dev/chainguard/static`.

You could use Google distroless if this mattered, but given the base image contents I doubt it really matters. Bulk of it is just `tzdata` (1MB) and `ca-certificates.crt` (220KB).
