### ISSUE TITLE
Improve Permission Formatting for Readability in Permify DSL

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#1628]
### Description:

The current permission syntax in Permify DSL allows defining complex logic within a single line. However, when the conditions become long or involve multiple logical operators, the line becomes difficult to read and understand. For example, the following permission definition is quite complex:

```perm
permission view = confidentiality_level_high(confidentiality_level) and parent.director or confidentiality_level_medium_high(confidentiality_level) and (parent.director or team.lead) or confidentiality_level_medium(confidentiality_level) and (team.lead or team.member) or confidentiality_level_low(confidentiality_level) and parent.member
```

This single-line format reduces readability and makes it challenging to maintain the code, especially for more complex permission logic. It would be helpful to support multi-line formatting, making the code easier to read and manage.

### Proposed Solution:

Introduce a syntax or formatting capability that allows permission definitions to be broken across multiple lines without changing the semantics of the logic. For example:

```perm
permission view = 
    confidentiality_level_high(confidentiality_level) and parent.director or
    confidentiality_level_medium_high(confidentiality_level) and (parent.director or team.lead) or
    confidentiality_level_medium(confidentiality_level) and (team.lead or team.member) or
    confidentiality_level_low(confidentiality_level) and parent.member
```

This format is much more readable and easier to understand.

### Benefits:

- Improves readability of complex permission logic.
- Makes code maintenance easier.
- Reduces the likelihood of errors in permission definitions.

**Comment by theoriginalstove** [comment]
@tolgaOzen I'm guessing this would involve updating the parser for the DSL? Is this something I could take?

**Comment by tolgaOzen** [comment]
Hi @theoriginalstove , thank you for your contribution 🚀

**Comment by theoriginalstove** [comment]
Anytime! Thanks for the quick review.
