### ISSUE TITLE
Unit Test of postgres relationshipWriter repository

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#166]
Writing unit tests for internal/repositories/postgres relationshipWriter repos.

**Comment by anascann** [comment]
can you please assign this task to me? thanks @EgeAytin

**Comment by EgeAytin** [comment]
@anascann done, happy hacking ☄️

**Comment by EgeAytin** [comment]
Hey @anascann, any progress on this one?  👀 👀
