### ISSUE TITLE
Subject filtering according to entity

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#176]
Getting all the users and their permissions to a specific resource?

Example:
in organization:1
user:1 is owner
user:2 is member
user:3 is member

I would like something like this:
Request: which users have access to organization:1
Response: [ "user:1#owner", "user:2#member", "user:3#member" ]

**Comment by ioneyed** [comment]
This would be beneficial both ways -

"What are all the relationships to Organization:1" -> user:1#owner, user:2#member...
"What are all the relationships for User:1 " -> organization:1#owner, repository:3#maintainer
