### ISSUE TITLE
SchemaWrite Request gives TenantId value length error

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#189]
When trying below following request with pasting the the schema directly in from the playground,
```
const client = new permify.grpc.newClient({
  endpoint: 'localhost:3478',
})

export const schemaWrite = async () => {
  try {
    const response = await client.schema.write({
      tenantId: 't1',
      schema: `"entity user {}\n        \nentity group {\n    relation member @user\n    \n}"`,
    })

    if (response) {
      console.log('response', response)
    }
  } catch (err) {
    console.log('err', err)
  }
}

schemaWrite()
```
It gives this following tenantıd value length error: "TenantId: value length must be at most 64 bytes"

```
err ClientError: /base.v1.Schema/Write INVALID_ARGUMENT: invalid SchemaWriteRequest.TenantId: value length must be at most 64 bytes
    at wrapClientError (/Users/brandensilva/projects/nextjs/nexthub/node_modules/.pnpm/nice-grpc@2.1.0/node_modules/nice-grpc/lib/client/wrapClientError.js:9:16)
    at Object.callback (/Users/brandensilva/projects/nextjs/nexthub/node_modules/.pnpm/nice-grpc@2.1.0/node_modules/nice-grpc/lib/client/createUnaryMethod.js:27:66)
    at Object.onReceiveStatus (/Users/brandensilva/projects/nextjs/nexthub/node_modules/.pnpm/@grpc+grpc-js@1.8.7/node_modules/@grpc/grpc-js/build/src/client.js:192:36)
    at Object.onReceiveStatus (/Users/brandensilva/projects/nextjs/nexthub/node_modules/.pnpm/@grpc+grpc-js@1.8.7/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/Users/brandensilva/projects/nextjs/nexthub/node_modules/.pnpm/@grpc+grpc-js@1.8.7/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/brandensilva/projects/nextjs/nexthub/node_modules/.pnpm/@grpc+grpc-js@1.8.7/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  path: '/base.v1.Schema/Write',
  code: 3,
  details: 'invalid SchemaWriteRequest.TenantId: value length must be at most 64 bytes'
```

**Comment by brandensilva** [comment]
Just an update on this. I've removed the double quotes from the schema attribute and still see the same issue.

export const will only work if it is a mjs file. I've since converted it to a cjs file so you'd need to remove the export for that.

**Comment by brandensilva** [comment]
This is also with the brew method of running Permify. I ran into issues with the docker method which I'll work with you on separately.

**Comment by brandensilva** [comment]
Some additional details:

Node version: 16.18.0
computer: Macbook Pro 2021 M1 Max (Apple Silicon)
OS: Ventura 13.1 (22C65)
Postgres version: 15.1 (via docker-compose)

permify-node version: 0.3.1
permify version: 0.3.0

**Comment by brandensilva** [comment]
I did try downgrading permify-node to 0.2.0 but still had no success with that.

**Comment by brandensilva** [comment]
I wasn't able to figure out why permify-node has issues around the tenantId getting passed into schema write. My guessing is more research and fixes will need to be applied into permify-node to move past these issues. Possibly something to do with nice-grpc and whatever "invalid argument" gets passed into that package.

I don't have time to dig that deep so hopefully you can find this in your code.

For now to work around this we've since moved to posting directly to WriteDB over http POST to deploy the schema.perm file script. My hope is that the permify-node permission check still works with GRPC so we can rely on the bit nicer dx around that rather than http/rest but we haven't gotten that far yet.

**Comment by EgeAytin** [comment]
Hi @brandensilva we solved the issue!! Could you install the latest version of [permify-node (0.3.2)](https://www.npmjs.com/package/@permify/permify-node) and test it. We can close this issue afterwards.

**Comment by brandensilva** [comment]
@EgeAytin I have confirmed that this fixed the issue, thanks!
