### ISSUE TITLE
ENV variables support

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#217]
The Permify server should support environment variables for configuration.

**Comment by AnonymousArthur** [comment]
Hi, could you clarify how to setup ENVs in documentation? I can't find it.
For example, given
```
# yaml file
tracer:
  exporter: otlp
```
It should have command equivalent
```
# command
--tracer-exporter=otlp
```
How about ENVs?
```
# ENV Variable
TRACE_EXPORTER=otlp
```
? I'm not sure about this setup

**Comment by AnonymousArthur** [comment]
Hey I found it in source code:  https://github.com/Permify/permify/blob/54fb80da9fb2fce77c956a4b218a061039fc2635/pkg/cmd/flags/serve.go#L279

It would be nice to have them documented.
