### ISSUE TITLE
New authentication method: OIDC (OpenID connect)

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#267]
The purpose of this issue is to add a new authentication method to secure access to the Permify instance. This authentication method will integrate with existing IDP solutions to validate JSON Web Tokens (JWTs) using JSON Web Keys (JWKs). By doing so, only trusted tokens from the IDP will be accepted for authentication, making the Permify instance more secure.

## Must to have
1. [AuthClaims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) should contain claims that are included in the [OpenID Connect (OIDC) standard claims](https://openid.net/specs/openid-connect-core-1_0.html#IDToken).
2. The implementation of this authentication method should be located in a specific folder, such as internal/authn/oidc.
3. The OIDC authentication method should be able to use JWKs provided by the IDP to validate JWTs.
4. The settings related to integrating with the IDP and validating JWTs using JWKs should be adjustable via configuration flags or files.

   - Predicted config fields: 

     |   name   |  type  |   default |
     | -------- | ----- | --------- |
     |   authn-oidc-audience  |  string | empty string |
     |   authn-oidc-issuer  |  string | empty string |

## Implementation Steps
1. The first step is to send an HTTP request to the issuer's well-known endpoint. This is a standardized endpoint that allows applications to discover information about the OpenID Connect provider. The endpoint is located at {issuer_url}/.well-known/openid-configuration. The response from this endpoint should include the issuer and jwks_uri values, which will be used in subsequent steps.
    * The issuer is the unique identifier for the OpenID Connect provider. It should be a URL that uniquely identifies the provider, and should match the iss claim in any JWTs that are issued by the provider.
    * The jwks_uri is the location of the JSON Web Key Set (JWKS) that the provider uses to sign its JWTs.

2. The next step is to send an HTTP request to the jwks_uri that was obtained in step 1. This will retrieve the JWKS, which is a collection of public keys that can be used to verify the signatures on JWTs issued by the provider.
    * The JWKS is a JSON object that contains an array of key objects. Each key object represents a public key that can be used to verify a JWT signature. The kid property in each key object is used to identify the key that was used to sign a particular JWT.

3. The next step, for each incoming request (whether it's a unary or stream request), the application should use an OidcAuthenticator (or similar struct) to parse the JWT and verify its claims. The claims in the JWT will depend on the specific implementation of the OpenID Connect provider, but they might include things like the subject (i.e. the user ID), the audience (i.e. the intended recipient of the JWT), and various other metadata.

    * If the JWT is invalid (i.e. if it has an invalid signature, is expired, or has other invalid claims), the OidcAuthenticator should return an error. Otherwise, the application can proceed with handling the request.

4. Finally, the new method must be registered as middleware (unary and stream) in the 'internal/servers/server.go' file.

The codebase of where the new option will be added:
<img width="1162" alt="Screenshot 2023-02-19 at 4 37 44 PM" src="https://user-images.githubusercontent.com/39353278/219985972-d0725941-ddff-4375-97e4-a9a693568d00.png">

## Note 
To use or test this OIDC authentication method, you will need to obtain two pieces of information from your OpenID Connect provider:
1. The OIDC issuer URL: This is the URL of the provider that is responsible for authenticating users. You will use this URL to discover information about the provider in step 1 of the authentication process.
2. The audience: This is the client ID of the application you're developing. It is a unique identifier that is assigned to your application by the OpenID Connect provider, and it should be included in the JWTs that are issued by the provider.

**Comment by mtyazici** [comment]
Can you assign the issue to me?

**Comment by EgeAytin** [comment]
Done! Happy Hacking @mtyazici 🚀
