### ISSUE TITLE
ERROR_CODE_SUBJECT_RELATION_CANNOT_BE_EMPTY while trying to create new relationship [BUG]

### ISSUE THREAD

**Issue by tarekdiflexmo** [Permify/permify#268]
**Describe the bug**
I am trying to create a relationship using the write relationship method, but I keep getting an error "ERROR_CODE_SUBJECT_RELATION_CANNOT_BE_EMPTY" with one of the relationships that I am trying to write.

**To Reproduce**
Permify running in Docker using: 
``` docker
docker run -p 3476:3476 -p 3478:3478 ghcr.io/permify/permify serve
```
``` Version: v0.3.0 ```

Schema:
```
entity user {}

entity organization {

	// organizational roles
	relation admin @user
	relation member @user

}

entity repository {

	// represents repositories parent organization
	relation parent @organization

	// represents owner of this repository
	relation owner  @user

	// permissions
	action edit   = parent.admin or owner
	action delete = owner
} 
```

Write request: 
``` curl
curl --location --request POST 'http://localhost:3476/v1/tenants/1/relationships/write' \
--header 'Content-Type: application/json' \
--data-raw '{
    "metadata": {
        "schema_version": "cfqfps6t9kmilbvbvj40"
    },
    "tuples": [
        {
        "entity": {
            "type": "repository",
            "id": "1"
        },
        "relation": "parent",
        "subject":{
            "type": "organization",
            "id": "test"
        }
    }
    ]
}'
```
Response 500 Internal Server Error:
``` json
{
    "code": 2,
    "message": "ERROR_CODE_SUBJECT_RELATION_CANNOT_BE_EMPTY",
    "details": []
}
```

**Expected behavior**
The relationship tuple should get created

**Additional context**
Other relationships are working as expected. For example the following request doesn't generate any errors:
Request:
``` curl
curl --location --request POST 'http://localhost:3476/v1/tenants/1/relationships/write' \
--header 'Content-Type: application/json' \
--data-raw '{
    "metadata": {
        "schema_version": "cfqfps6t9kmilbvbvj40"
    },
    "tuples": [
        {
        "entity": {
            "type": "repository",
            "id": "1"
        },
        "relation": "owner",
        "subject":{
            "type": "user",
            "id": "tester"
        }
    }
    ]
}'
```
Response 200 OK:
``` json
{
    "snap_token": "lXYQtY7mRRc="
}
```

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: Windows 11 with Docker for Windows
 - Version 0.3.0

**Comment by tolgaOzen** [comment]
Hi @tarekdiflexmo, this is not a bug

<img width="1357" alt="Screenshot 2023-02-21 at 9 45 54 AM" src="https://user-images.githubusercontent.com/39353278/220420746-352d66d1-8a1f-494b-9570-348f76a7fec5.png">

In your example
- repository:1#owner@organization:1#admin -> admins of organization 1 is owner of repository 1
- repository:1#parent@organization:1#... -> parent of repository 1 is organization 1
- repository:1#owner:user:1 -> user 1 is owner of repository 1

Can you change your query with this?

```
curl --location --request POST 'http://localhost:3476/v1/tenants/1/relationships/write' \
--header 'Content-Type: application/json' \
--data-raw '{
    "metadata": {
        "schema_version": "cfqfps6t9kmilbvbvj40"
    },
    "tuples": [
        {
        "entity": {
            "type": "repository",
            "id": "1"
        },
        "relation": "parent",
        "subject":{
            "type": "organization",
            "id": "test",
            "relation": "..."
        }
    }
    ]
}'
```

**Comment by tarekdiflexmo** [comment]
Hi @tolgaOzen thank you for the quick answer!

Your explanation is quite clear. However, I feel that there is a special treatment to the entity "user", am I correct in this assumption?

To explain what I mean, I will simplify the schema model to this:
```
entity user {}

entity organization {}

entity repository {

	relation parent @organization
	relation owner @user
}
```

To me, both parent and owner relations are exactly the same, one has a type user and the other uses the type organization.

This request:
``` curl
curl --location --request POST 'http://localhost:3476/v1/tenants/1/relationships/write' \
--header 'Content-Type: application/json' \
--data-raw '{
    "metadata": {
        "schema_version": "cfqghbhr6soaolsec2vg"
    },
    "tuples": [
        {
        "entity": {
            "type": "repository",
            "id": "1"
        },
        "relation": "owner",
        "subject": {
            "type": "user",
            "id": "tester"
        }
    }
    ]
}'
```
gives a correct response. However, the relationship against the parent relation:
``` curl
curl --location --request POST 'http://localhost:3476/v1/tenants/1/relationships/write' \
--header 'Content-Type: application/json' \
--data-raw '{
    "metadata": {
        "schema_version": "cfqghbhr6soaolsec2vg"
    },
    "tuples": [
        {
        "entity": {
            "type": "repository",
            "id": "1"
        },
        "relation": "parent",
        "subject":{
            "type": "organization",
            "id": "test"
        }
    }
    ]
}'
```
returns the error above.

I might be asking a stupid question here, but if I assume that the entities of user and organization are just entities, what makes a relationship against the owner relation (user) different than the parent relation (organization), where one requires the "relation": "..." and the other doesn't?

**Comment by tolgaOzen** [comment]
Hi @tarekdiflexmo, yes the assumption is right there is special treatment to the user entity. 

I understand what you're saying, it can be confusing. If you open a separate issue about it, we can build it for the next release.
