### ISSUE TITLE
Allow relationships to be created against non-user entity types without having to pass in the empty relation string "relation" = "..."

### ISSUE THREAD

**Issue by tarekdiflexmo** [Permify/permify#269]
**Is your feature request related to a problem? Please describe.**
When creating a relationship against a relation that takes in a "user" entity type, we don't have to pass in the empty relation string "relation" = "...". However, when creating a relationship against any other entity types, we need to pass that property. This can be confusing to the users of the API.

**Example**
Consider the following schema model:
```
entity user {}

entity organization {}

entity repository {

	relation parent @organization
	relation owner @user
}
```
To me, both parent and owner relations are exactly the same, one has a type user and the other uses the type organization.

This request:
``` curl
curl --location --request POST 'http://localhost:3476/v1/tenants/1/relationships/write' \
--header 'Content-Type: application/json' \
--data-raw '{
    "metadata": {
        "schema_version": "cfqghbhr6soaolsec2vg"
    },
    "tuples": [
        {
        "entity": {
            "type": "repository",
            "id": "1"
        },
        "relation": "owner",
        "subject": {
            "type": "user",
            "id": "tester"
        }
    }
    ]
}'
```
gives a correct response 200. 

However, a relationship against the parent relation:
``` curl
curl --location --request POST 'http://localhost:3476/v1/tenants/1/relationships/write' \
--header 'Content-Type: application/json' \
--data-raw '{
    "metadata": {
        "schema_version": "cfqghbhr6soaolsec2vg"
    },
    "tuples": [
        {
        "entity": {
            "type": "repository",
            "id": "1"
        },
        "relation": "parent",
        "subject":{
            "type": "organization",
            "id": "test"
        }
    }
    ]
}'
```
returns an error response
``` json
{
    "code": 2,
    "message": "ERROR_CODE_SUBJECT_RELATION_CANNOT_BE_EMPTY",
    "details": []
}
```

**Describe the solution you'd like**
Accept relationships against non-user types without the "relation" = "..." property and fill that behind the scenes automatically.

**Additional context**
This issue was initially opened as a bug #268, but later was found not to be a bug.

**Comment by brandensilva** [comment]
@EgeAytin This appears to be somewhat related to the issue I posted to you on Discord. But upon testing the new docker release of Permify you posted, I've been unable to even get the server to launch now to test if your changes addressed this error.

**Comment by brandensilva** [comment]
version 0.3.3 fixes any authn issues I was encountering so I could test this further. Also confirmed I needed a "..." for non-user entities which isn't abundantly clear that is needed anywhere in the documentation or if it can be improved from this issue by @tarekdiflexmo  with not needing it.

**Comment by brandensilva** [comment]
Note I tested this with a blank subject relation with `relation: ''`, added a subject that was on the given entity: `relation: 'admin'`, and tried with not passing any subject relation and it won't work as outlined in this issue without encountering subject relation errors. Only "..." works.

**Comment by tolgaOzen** [comment]
Hi @brandensilva we create this feature in v0.3.4, you can test it and we can close this issue afterwards.

**Comment by brandensilva** [comment]
Sounds great, thanks for the improvement. Let me give it a test either today or tomorrow.

**Comment by tarekdiflexmo** [comment]
@tolgaOzen Thanks for the improvement! I can confirm that this works now!
