### ISSUE TITLE
Error on Cloud66 deployment

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#275]
Encounter with en error when trying to deploy Permify to Cloud66: 

`Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"serve\": executable file not found in $PATH": unknown`

**Comment by kevintraver** [comment]
Changing the Cloud66 run **command** from `serve` to `permify serve` appears to work.

**Comment by EgeAytin** [comment]
Hı @kevintraver, I'm closing this issue since this issue seems solved.

**Comment by kevintraver** [comment]
Perhaps this could be updated in the Docker documentation to avoid future confusion?
