### ISSUE TITLE
CDC 

### ISSUE THREAD

**Issue by gedw99** [Permify/permify#32]
**Is your feature request related to a problem? Please describe.**

Reactive authourisation such that a change causes all micro services to see the altered authz rules .

**Describe the solution you'd like**

see above …

**Describe alternatives you've considered**

**Additional context**

I saw an issue relating to cdc 

Would be nice if SQLite and postresql are supported 

in terms of scoping I don’t know. A microservice subscribes for changes but how to scope ? Maybe tags .. not sure

**Comment by EgeAytin** [comment]
Hi we're not have CDC feature, we deprecated that almost 4 months ago and won't implement it further so I'm closing this issue.
