### ISSUE TITLE
[BUG] permissions/lookup-entity is not responding.

### ISSUE THREAD

**Issue by fatihhozturkk** [Permify/permify#330]
**Describe the bug**
API http://localhost:3476/v1/tenants/{{tenant_id}}/permissions/lookup-entity is not responding.

**To Reproduce**
-Open the post method http://localhost:3476/v1/tenants/{{tenant_id}}/permissions/lookup-entity.
-A random value is written to the "permission" value.
-Send to api. 
-No response appears.

**Expected behavior**
The api is expected to respond.

**Environment (please complete the following information, because it helps us investigate better):**
 - permify:v0.3.3

**Comment by brandensilva** [comment]
I wonder if this is related to my issue: https://github.com/Permify/permify/issues/313. Perhaps a response is given but the error is happening on the server rather than in your console.

**Comment by tolgaOzen** [comment]
Hi @brandensilva, it does not appear to be related. Your issue seems to be caused by a difference in the request body, while issue #330 is related to errors happening on the server. We have already solved issue #330 in pull request #334.
