### ISSUE TITLE
Add Search to Docs

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#386]
Add search to docs

**Comment by thecaffeinedev** [comment]
@EgeAytin I have created a PR for this.

I was facing some issues with the `@mdx-js/react` package.

I Installed [docusaurus-search-local](https://github.com/cmfcmf/docusaurus-search-local) for the search feature. Search is working as expected after `docusaurus build` and `docusaurus serve` . After build I checked all the pages and didn't find anything broken. 

Can you please review the PR once and suggest if any changes are needed? 

Thanks

**Comment by EgeAytin** [comment]
Hi @thecaffeinedev, thank you for your contribution. The only part that needs an improvement is the style of the search input. But we can handle that our side. Hope to wee you on other issues [👋](https://emojipedia.org/waving-hand/)
