### ISSUE TITLE
Action support upper case

### ISSUE THREAD

**Issue by ImKcat** [Permify/permify#404]
**Describe the bug**
I use the upper case action in the schema, I got this error when I trying to lookup an entity:
`rpc error: code = InvalidArgument desc = invalid PermissionLookupEntityRequest.Permission: value does not match regex pattern "^([a-z][a-z0-9_]{1,62}[a-z0-9])$"`

**To Reproduce**
1. Write schema:
```
entity user {

} 

entity organization {
	relation admin @user  
	relation user @user  

	action TEST_ACTION = admin
} 
```
2. Create tenant `test`
3. Create a relationship with `v1/tenants/test/relationships/write`: 
```
{
	"metadata": {
		"schema_version": "cgun1o095oqs73b2vt00"
	},
	"tuples": [
		{
			"entity": {
				"type": "organization",
				"id": "o1"
			},
			"relation": "admin",
			"subject": {
				"type": "user",
				"id": "u1"
			}
		}
	]
}
```
4. Lookup entity with `/v1/tenants/test/permissions/lookup-entity`:
```
{
	"metadata": {
		"schema_version": "cgun1o095oqs73b2vt00",
		"depth": 100
	},
	"entity_type": "organization",
	"permission": "TEST_ACTION",
	"subject": {
		"type": "user",
		"id": "u1"
	}
}
```
5. Got error:
```
{
	"code": 3,
	"message": "invalid PermissionLookupEntityRequest.Permission: value does not match regex pattern \"^([a-z][a-z0-9_]{1,62}[a-z0-9])$\"",
	"details": []
}
```

**Comment by tolgaOzen** [comment]
Hello @ImKcat, we have resolved this issue and you can check it out here (https://github.com/Permify/permify/pull/405). It will be fixed in the upcoming v0.3.9 release. We are planning to release it by next week at the latest. Thank you.

**Comment by tolgaOzen** [comment]
Hello @ImKcat, we have released a fix and solved the problem. Could you please test it and, if there are no remaining issues, close the issue?

**Comment by ImKcat** [comment]
> Hello @ImKcat, we have released a fix and solved the problem. Could you please test it and, if there are no remaining issues, close the issue?

I have already tested it, and there are no issues. Thank you very much.
