### ISSUE TITLE
[BUG] (documentation) Kubernetes docs use nonexistent command line argument --database-name

### ISSUE THREAD

**Issue by andrewspiers-csiro** [Permify/permify#410]
**Describe the bug**
Over at https://docs.permify.co/docs/installation/kubernetes#deploying--running-permify-in-nodes
There is a sample deployment that mentions a --database-name argument, but permify fails to start, telling me:

kubectl -n permify logs deployment/permify -c permify
Error: unknown flag: --database-name
Usage:
  permify serve [flags]

**To Reproduce**
Follow the kubernetes example. I'm using GKE, but this shouldn't matter.

**Expected behavior**
I think the db name can just be provided as part of the database URI?

**Comment by thecaffeinedev** [comment]
I have created a PR for this #416. Do let me know if I need to make any other changes for this.

**Comment by tolgaOzen** [comment]
Hey @thecaffeinedev, Thank you for your contribution. Everything seems clear, and there are no issues.
