### ISSUE TITLE
Playground Graph Relation Bug on Visualizer

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#43]
Graph relation bug on Permify Playground Visualizer, according to the model below the edit relations parent.admin and owner on the Visualizer should be connected with **or** not **and**

``` 
entity user {}
        
entity organization {

    // organizational roles
    relation admin @user
    relation member @user
    
}

entity repository {

    // represents repositories parent organization
    relation parent @organization
    
    // represents owner of this repository
    relation owner  @user
    
    // permissions
    action edit   = parent.admin or owner
    action delete = owner
    
} 
```

<img width="422" alt="Screen Shot 2022-12-10 at 13 19 20" src="https://user-images.githubusercontent.com/34595361/206849801-6e77b679-4ef0-4668-9f68-287375e04ed4.png">

**Comment by luco5826** [comment]
It is not just the visualization, also the actual check doesn't work. In the example you provided, if you create

![immagine](https://user-images.githubusercontent.com/38291180/207856013-8e3612c8-c9aa-4cd3-b2e6-c9844a29231f.png)

And

![immagine](https://user-images.githubusercontent.com/38291180/207856065-2c9cd01f-f067-4155-8f66-c591fb958c36.png)

The check

```
can user:1 edit repository:1
```

Fails, while it should work given the fact that either the organization admin OR the repository owner can edit the repository

**Comment by EgeAytin** [comment]
Hi @luco5826, we have tried the check "can user:1 edit repository:1" and got success result as shown below.

![Screen Shot 2022-12-15 at 15 23 11](https://user-images.githubusercontent.com/34595361/207858331-df95ec76-9e31-4181-b406-e9787e12986b.png)

Could you send the model you're trying with ?

**Comment by EgeAytin** [comment]
Second relation tuple - ```repository:1#parent@organization?1``` - is wrong formatted and its causing the false negative result. It should be: ```repository:1#parent@organization?1...```

The “...” used when subject type is different from user entity. #… represents a relation that does not affect the semantics of the tuple. 
![Screen Shot 2022-12-15 at 15 57 05](https://user-images.githubusercontent.com/34595361/207864726-4c4fe639-9745-483e-8a2b-6249fcc60c49.png)
Actually we covered it on our [docs](https://docs.permify.co/docs/getting-started/sync-data#parent-organization) but we'll look for solutions to prevent the creation of malformed tuples.

**Comment by EgeAytin** [comment]
To be honest, we can detect the type of the subject with different ways and not use the "..." suffix as you mentioned. But we want to be faithful to the Google Zanzibar paper and leave that with the suffix. Here is some example relation tuples from the Google Zanzibar paper: 
<img width="741" alt="Screen Shot 2022-12-15 at 16 49 37" src="https://user-images.githubusercontent.com/34595361/207875556-b3a71c05-99ec-48df-ad94-3033d5fc55b9.png">

Apart from this, no worries for the questions we'd love to hear from you. So please feel free to ask any questions related Permify or authorization, join our discord to discuss, or schedule a call anytime you're available :)

**Comment by luco5826** [comment]
Thank you very much. You've been very helpful and I really look forward to integrating permify in my projects, thanks!
