### ISSUE TITLE
Custom roles

### ISSUE THREAD

**Issue by leonard-henriquez** [Permify/permify#432]
Does Permify allow to create custom roles defined by the application at runtime ?
Could you provide an example ? 

Here is an example of how it's possible to create custom roles in Oso:
https://www.osohq.com/docs/guides/model-your-apps-authz#custom-roles

**Comment by EgeAytin** [comment]
Hi @leonard-henriquez, we don't have a custom roles feature and not in our roadmap for near future to be honest.

**Comment by AnonymousArthur** [comment]
> Hi [@leonard-henriquez](https://github.com/leonard-henriquez), we don't have a custom roles feature that defined by the runtime and to be honest for the near future it probably won't be our priority.

Hi, wondering why your team decided to put it at low priority? The use case of customizable role groups for toB or toO products is actually very common.

Any other options that I can explore based on your authorization expertise?
