### ISSUE TITLE
Migration Command

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#44]
### Issue Summary:

The purpose of this issue is to request the addition of a new `migrate` command to our application's CLI. The `migrate` command should use the Goose library to apply database migrations, and should be implemented using the Cobra library. The command should include flags for specifying the database engine and database URI.

### Expected Behavior:

The migrate command should have the following behavior:

- It should accept a `direction` flag to specify whether to apply migrations (`up`), rollback migrations (`down`), or check the status of migrations (`status`).
- It should accept a `target` flag to specify the target version for the migration.
- It should accept an `database_engine` flag to specify the database engine (e.g. postgres).
- It should accept a `database_uri` flag to specify the URI of the database to apply the migration to.
- It should use the Goose library to apply the appropriate migration command based on the `direction` flag, using the specified database engine and database URI.
- It should output success or failure messages for the migration command.

Permify currently uses the Cobra library to implement its CLI. We believe that adding a migrate command to the CLI would make it easier for developers to manage database migrations, and would ensure that all developers are using a consistent migration tool.

We would like the implementation of the migrate command to be consistent with the rest of the application's CLI, and to follow best practices for CLI design and implementation.

### Potential Solution:

We suggest implementing the migrate command using the Cobra library, with the following structure:

```ssh
$ permify migrate up --target=<version> --database-engine=<engine> --database-uri=<database_uri>
$ permify migrate down --target=<version> --engine=<engine> --database-uri=<database_uri>
$ permify migrate status --database-engine=<engine> --database-uri=<database_uri>
```
This structure should be familiar to developers who are already using the application's CLI, and should make it easy to manage database migrations.

The implementation of the migrate command should use the Goose library to apply the appropriate migration command based on the direction flag, using the specified database engine and database URI. The implementation should also provide informative success or failure messages for the migration command.

We can discuss the specific details of the implementation in the comments of this issue.

**Note:** 
migration files are in the `internal/repositories/postgres/migrations` directory

**Comment by muratmirgun** [comment]
Can you assign this task to me?

**Comment by EgeAytin** [comment]
Done! Happy Hacking @muratmirgun
