### ISSUE TITLE
Deeply Tracing With Open Telemetry

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#46]
**Problem:**
Users need better tracing and data analysis on the Permify.

**Specifications:**
Users should be able to trace the performance in every function of the application via [Open Telemetry](https://github.com/open-telemetry/opentelemetry-go). Currently users can only trace request on high level; as example we trace check requests performance as below:

```
func (r *PermissionServer) Check(ctx context.Context, request *v1.PermissionCheckRequest) (*v1.PermissionCheckResponse, error) {

	ctx, span := tracer.Start(ctx, "permissions.check")
	defer span.End()

	..
        ..
        ..
}
```
The workflow is,  above server/check function calls to services/check function, then calls commands/check etc . We want users to trace every point in a single process of coming requests, not just the function on the highest level.

**Comment by Ahmadkashif** [comment]
Hey @EgeAytin I would like to help on this...

**Comment by EgeAytin** [comment]
Hi @Ahmadkashif, thats great!! you can start with adding the same functionality (tracing) to the functions on _internal/commands_ and _internal/services_ folders. Moreover, we can work together and improve this usage with parameters or other options of Open Telemetry. If you're okey I'll assing you to this task :)

If you have any questions or need help related with this issue, ask me freely: ege@permify.co

**Comment by EgeAytin** [comment]
@Ahmadkashif Done! Happy hacking 💥

**Comment by EgeAytin** [comment]
Hey @Ahmadkashif, any progress on this one? We're excited to see your changes here 👀 👀

**Comment by Ahmadkashif** [comment]
@EgeAytin @tolgaOzen Hey guys. I have covered deep tracing on 3 major servers ( permissions, relationships and schemas ).

I can see the PRs were merged. Lets close this issue then?
