### ISSUE TITLE
Feature: Attribute Based Authz Control (ABAC)

### ISSUE THREAD

**Issue by sashokbg** [Permify/permify#469]
Feature: Attribute Based Authz Control (ABAC)

As a developer
I want to define authroziation policies that are based on principal or entity attributes
So that I can create rich and precise business driven rules

Example:
- Add a policy that restricts a resource for all users that are less than 18 years old
- Add a policy that restricts access to a bank account when X amount of money has been transfered this month

**Technical Notes**
Maybe some JS callbacks can be added similar to what keycloak does ?

Thank you for your project and great work !
Best Regards
Aleks

**Comment by EgeAytin** [comment]
Hi @sashokbg, we already have a ABAC support issue, and it will cover the examples you provided above when finished. You can track the issue from: https://github.com/Permify/permify/issues/255 and share your thoughts.
