### ISSUE TITLE
provide an API to fetch "what actions user:x can perform on entity:y"

### ISSUE THREAD

**Issue by liuhx1027** [Permify/permify#477]
**Is your feature request related to a problem? Please describe.**
When applying permission controls on frontend, we often need to get a list of permissions that user can perform on a certain object so that we can hide/display the corresponding button(s) or page(s). it is tedious and less performant to ask each permission/action using the "check" API endpoint provided by permfiy as of now, since we will have to fire many calls (one per permission/action) to permify from frontend to get such info.

**Describe the solution you'd like**
Having a dedicated API endpoint to fetch such info in one call from permify.

**Describe alternatives you've considered**
if such API cannot be added to permify, we would need need wrap such API endpoint by calling permify api multiple times (one for each action). it will become worse when new action being added

**Additional context**

**Comment by EgeAytin** [comment]
We concluded this issue with the development of the Subject Permission List endpoint. Here is the related documentation: https://docs.permify.co/docs/api-overview/permission/subject-permission/
