### ISSUE TITLE
[BUG] Playground schema validation does not support attribute array types

### ISSUE THREAD

**Issue by DeanBruntThirdfort** [Permify/permify#631]
**Describe the bug**
When entering a schema in the playground that has an array attribute, the language validation red lines the square brackets incorrectly.
Additionally, this seems to prevent the schema "saving" in the playground and allowing the object types to be used in the data tab etc.

**To Reproduce**
Create a schema in the playground that uses an array attribute type on an entity. E.g: this example from [here](https://docs.permify.co/docs/use-cases/abac#2-string) fails:
```
entity user {}

entity organization {
    
    relation admin @user

    attribute location string[]

    permission view = check_location(request.current_location, location) or admin
}

rule check_location(current_location string, location string[]) {
    current_location in location
}
```

**Example Application**
N/A

**Expected behavior**
I expect the schema to be accepted and validate properly, further allowing it to then be used in the data tab in the playground.

**Additional context**
There also seems to be a related issue where usage of array types within a rules argument types (when validation gets that far) causes the playground's backing application to panic.

**Environment (please complete the following information, because it helps us investigate better):**
I observed this behaviour in the publicly available playground at play.permify.co
I can't see any mention of what version this uses on the frontend, but I tested the issue at 25/08/2023 12:05 if that helps pinpoint what version is deployed.

**Comment by tolgaOzen** [comment]
Hi @DeanBruntThirdfort , thanks for the issue. We have also encountered some errors with string array recently in the beta version of ABAC. Due to this, we’ve temporarily removed the array feature until we can resolve this issue. We are actively working on a fix. We will update you about this soon 👍

**Comment by DeanBruntThirdfort** [comment]
> Hi @DeanBruntThirdfort , thanks for the issue. We have also encountered some errors with string array recently in the beta version of ABAC. Due to this, we’ve temporarily removed the array feature until we can resolve this issue. We are actively working on a fix. We will update you about this soon 👍

So to confirm, this isn't actually a bug, it's just a consequence of arrays for ABAC being temporarily removed whilst issues are resolved?

**Comment by tolgaOzen** [comment]
Yes, we have temporarily removed it from the beta, and we are working on resolving the issues.

**Comment by tolgaOzen** [comment]
Hi @DeanBruntThirdfort, we've resolved the issue with array data types and have updated our playground. I wanted to keep you informed.

**Comment by DeanBruntThirdfort** [comment]
> Hi @DeanBruntThirdfort, we've resolved the issue with array data types and have updated our playground. I wanted to keep you informed.

🎉 Thanks for the update
