### ISSUE TITLE
Allowing "." character in tuple creation

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#758]
If I post to http://localhost:3476/v1/tenants/t1/relationships/write with data

```
{
    "metadata": {
    },
    "tuples": [
        {
            "entity": {
                "type": "organization",
                "id": "org.2WffVF27PL5VO00JcqYYhiq42m6"
            },
            "relation": "member",
            "subject": {
                "type": "user",
                "id": "acct.2WffVEDWStT0jfiBlcO9vjcwQpd"
            }
        }
    ]
}
```

```
Invalid RelationshipWriteRequest.Tuples[0]: embedded message failed validation | caused by: invalid Tuple.Entity: embedded message failed validation | caused by: invalid Entity.Id: value does not match regex pattern \"^(([a-zA-Z0-9_][a-zA-Z0-9_|-]{0,127})|\\\\*)$\"",
```

We tend to use these style of ids in our app to make it easier to identify some entity ID.

Is there a work around? The only thing I can think of is making a custom client which can encode/decode values... which is not really fun.

**Comment by nguyenluan2001** [comment]
Hi sir, can i work on this issue?

**Comment by EgeAytin** [comment]
Hi @nguyenluan2001 assigned to you. Happy hacking ✌🏻

**Comment by ahmethakanbesel** [comment]
Hi, 
I can look into this issue.
Could you assign it to me?

**Comment by EgeAytin** [comment]
Hi @ahmethakanbesel yes you can. Happy hacking ✌🏻
