### ISSUE TITLE
Implement Client-Side Authentication Methods for Consistent Hashring

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#770]
### Overview

While the Permify servers currently communicate in an insecure manner, we've spotted an opportunity in the NewCheckEngineWithBalancer function (found within internal/engines/balancer/balancer.go) to enhance this security. The authn configuration is already provided, but the client-side authentication using both a pre-shared key and OIDC has yet to be implemented.

### Task

**Implement the Authentication Options:**

**For Pre-shared Key:**
- Initialize the KeyAuthn structure using the provided authn configuration.
- Convert the KeyAuthn instance into PerRPCCredentials.
- Append grpc.WithPerRPCCredentials() to the options slice.

**For OIDC:**

- Set up the client-side authentication mechanism using an OIDC provider, initializing and configuring an OIDC client accordingly.
- Convert the OIDC token into a PerRPCCredentials suitable for gRPC.
- Add the OIDC credentials to the options slice using grpc.WithPerRPCCredentials().

```
// TODO path: internal/engines/balancer/balancer.go
// Enhance client-side authentication mechanisms:
// 1. Use a pre-shared key from KeyAuthn.
// 2. Incorporate OIDC authentication.
```

Current Implementation

For context, the current code section looks like:

```go
var err error

var options []grpc.DialOption

var creds credentials.TransportCredentials

if srv.TLSConfig.CertPath != "" && srv.TLSConfig.KeyPath != "" {
    creds, err = credentials.NewClientTLSFromFile(srv.TLSConfig.CertPath, srv.TLSConfig.KeyPath)
    if err != nil {
        return nil, fmt.Errorf("could not load TLS certificate: %s", err)
    }
} else {
    creds = insecure.NewCredentials()
}

// TODO: Add client-side authentication using a key from KeyAuthn.
// 1. Initialize the KeyAuthn structure using the provided configuration.
// 2. Convert the KeyAuthn instance into PerRPCCredentials.
// 3. Append grpc.WithPerRPCCredentials() to the options slice.
```

Guidance

This is marked as a "good first issue", ideal for individuals new to our codebase and wanting to understand more about our security and authentication processes. You're welcome to work on either of the authentication methods or both. Should you have questions, our team is ready to assist.

**Comment by obakeng-develops** [comment]
Hey, I'd like to give this a Go.

**Comment by tolgaOzen** [comment]
Hi @obakeng-develops , issue is all yours. Happy hacking 🙌🏼
