### ISSUE TITLE
[BUG] Anchor links don't work in docs

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#775]
When I entered the URL https://docs.permify.co/docs/api-overview/data/write-data#creating-attribute-data, it should have redirected me to the "Creating Attribute Data" section on the page, but instead, it threw me to the top as no anchor tags were provided.

**Comment by ahmethakanbesel** [comment]
Hi,

I couldn't reproduce the issue on my localhost but I guess it's related to the `trailingSlash` config in `docusaurus.config.js`. As mentioned here: https://stackoverflow.com/questions/71711287/brief-http-404-error-on-all-pages-in-docs
If you can assign the issue to me, I can open a PR for it.

**Comment by EgeAytin** [comment]
Hi @ahmethakanbesel, issue is all yours. Happy hacking 🙌🏼
