### ISSUE TITLE
https://docs.permify.co/docs/getting-started/modeling/examples/ This page is blank 

### ISSUE THREAD

**Issue by m3rashid** [Permify/permify#806]
**Describe the bug**
Missing page contents [PAGE NOT FOUND ERROR]

**To Reproduce**
Just go to https://docs.permify.co/docs/getting-started/modeling/examples/ in the docs

**Expected behavior**
Real life examples link directed from https://docs.permify.co/docs/getting-started/modeling/ this page (at the bottom, just above the doccusaurus footer) should preview real life examples

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: [any]
 - Version [0.5x]

**Comment by EgeAytin** [comment]
Thank you for reporting the issue, @m3rashid. If you're available to work on this, I can assign it to you. If not, we'll resolve it in a matter of hours.

**Comment by berkeli** [comment]
I will work on this, noticed there are quite a few broken link in docs
