### ISSUE TITLE
Relationship Validation in Coverage Command

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#811]
### Description
The coverage command currently computes coverage without validating the relationships. This feature request is to enhance the coverage command so that it also validates each relationship before proceeding with the computation. This validation step will ensure that only correctly defined relationships are considered, which will improve the accuracy and reliability of the coverage results.

### Desired Behavior
When running the coverage command, it should first validate all the relationships against a set of predefined rules or schema. Once validation is passed, the command should then compute the coverage. This will help in early detection of misconfigurations or errors in relationship definitions.

### Impact
This feature will prevent incorrect relationships from being marked as covered and will also provide immediate feedback to the user if there are any issues with the relationship definitions, thus improving the overall quality and maintainability of the system.

**Comment by Min2who** [comment]
@tolgaOzen can you elaborate more on this issue
