### ISSUE TITLE
Adding Playground Sample App Examples to Docs [2/4]

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#814]
Add example Mercury's authorization schema to our documentation: https://play.permify.co/?s=mercury&tab=schema

It's expected to follow following context in the documentation page:

- Schema 
- Brief Examination of the Model
    - Entities & Relations
    - Permissions
   
Example documentation pages for sample apps: https://docs.permify.co/docs/getting-started/examples/

**Comment by saifxd7** [comment]
Please assign me!

**Comment by EgeAytin** [comment]
Hi @saifxd7, assigned. Happy hacking
