### ISSUE TITLE
 Postgres Index Optimization and Benchmarking

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#863]
## Introduction
This document outlines the process of optimizing indexes in a Postgres database and conducting before-and-after benchmarks to evaluate the performance impact of these optimizations on specific check queries.

## Repository File References
- **Migrations:** Located in [internal/storage/postgres/migrations](https://github.com/Permify/permify/tree/master/internal/storage/postgres/migrations)
- **Queries:** Located in [internal/engines](https://github.com/Permify/permify/tree/master/internal/engines)

### Initial Analysis
- **Description:** Assess the current indexing strategy and identify potential areas for improvement.
- **Tools Used:** [List any analysis tools or scripts used]
- **Findings:** Summarize the key findings from the initial analysis.

### Index Optimization
- **Optimization Strategies:** Detail the specific index optimizations implemented.
  - Strategy 1: [Description]
  - Strategy 2: [Description]
  - ...
- **Implementation Details:** Provide SQL commands or scripts used for the optimization.

### Environment Details
- **Postgres Version:** [Version]
- **Operating System:** [OS]
- **Hardware Specifications:** [Hardware details]

### Benchmarking Methodology
- **Queries Tested:** List the check queries used for benchmarking, as found in the `internal/engines` folder.
  - Query 1: `SQL statement`
  - Query 2: `SQL statement`
  - ...
- **Procedure:** Describe the benchmarking process, including how many times each query is run and how metrics are collected.

### Before Optimization
- **Query 1:** 
  - Average Execution Time: [Time]
  - Additional Metrics: [Any other relevant metrics]
- **Query 2:** 
  - Average Execution Time: [Time]
  - Additional Metrics: [Any other relevant metrics]
- ...

### After Optimization
- **Query 1:** 
  - Average Execution Time: [Time]
  - Additional Metrics: [Any other relevant metrics]
- **Query 2:** 
  - Average Execution Time: [Time]
  - Additional Metrics: [Any other relevant metrics]
- ...

## Analysis and Conclusions
- **Performance Improvements:** Highlight the key improvements in query performance post-optimization.
- **Recommendations:** Offer any further recommendations based on the benchmarking results.

## Appendix
- **Additional Notes:** [Any other notes or observations]
- **Scripts/Commands Used:** Provide any scripts or commands used during the optimization and benchmarking process.

**Comment by tolgaOzen** [comment]
@saifxd7, I have assigned this task to you. Happy hacking 🚀

**Comment by Min2who** [comment]
Hi @tolgaOzen  i have initially seen the issues and have made the initial analysis of the database . Should i share how i would approach for optimizing the database?

**Comment by tolgaOzen** [comment]
Hello @Min2who, @saifxd7 is currently dealing with the issue. You can share it with him or you can collaborate with him on the development

**Comment by Min2who** [comment]
@saifxd7 are you still working?

**Comment by saifxd7** [comment]
Yes @Min2who, I'm working on it!

**Comment by tolgaOzen** [comment]
Hello @saifxd7, firstly, we have reviewed your PR and changing old migration files is dangerous for those who previously used Permify and should not be done. Additionally, since we want this issue to be analyzed more thoroughly, we would like to assign one more person to elaborate on it.

**Comment by Min2who** [comment]
i would like to work in it.If you can assign me

**Comment by tolgaOzen** [comment]
@Min2who, I'm assigning you. Happy hacking 🚀

**Comment by tolgaOzen** [comment]
Hello @Min2who, are there any updates?

**Comment by Min2who** [comment]
> Hello @Min2who, are there any updates?

Hey @tolgaOzen was travelling for a bit. I will submit my progress in a week. Is it fine ?

**Comment by Rutik7066** [comment]
Hi @tolgaOzen could you please assign to me

**Comment by ayewo** [comment]
Throwing my hat in the ring with an /attempt #863

**Comment by tolgaOzen** [comment]
Hi @ayewo, I'm assigning you. Happy hacking 🚀

**Comment by tolgaOzen** [comment]
Hello @ayewo, is there any progress?

**Comment by mohanish2504** [comment]
I will like to add my name in queue @tolgaOzen.

I have good experience with Postgres indexes.

references:
1. https://medium.com/@mohanishp1/optimizing-time-series-queries-b9fe7715ccea
2. https://medium.com/@mohanishp1/indexing-a-blessing-in-vertical-scaling-e037c3063b05

**Comment by ayewo** [comment]
Hey @tolgaOzen 

Thanks for the status check. I fell ill and I’m still recovering. Hopefully I’ll be able to continue this week.

**Comment by Rutik7066** [comment]
Hi @ayewo are you working on this?

**Comment by mohanish2504** [comment]
Hey @tolgaOzen I would like to contribute to this issue if @ayewo is not working.
@ayewo please let us know.

**Comment by ayewo** [comment]
I'm feeling much better and have already started working on this!

**Comment by Rutik7066** [comment]
Hey @ayewo can we collaborate?

**Comment by tolgaOzen** [comment]
Hello @ayewo, is there any progress?
