### ISSUE TITLE
[BUG] Button Alignment Issue in Playground

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#872]
**Describe the bug**
The Save and Cancel buttons in the Playground Relationship Section are not aligned correctly. Window size: 1440x398
<img width="1429" alt="Screen Shot 2023-11-23 at 18 59 57" src="https://github.com/Permify/permify/assets/34595361/4e018f72-2ea9-4052-b15e-feb035b0f1f0">

**Comment by Jilesh980** [comment]
hi @EgeAytin can i work on this issue and fix this.
Thank you.

**Comment by EgeAytin** [comment]
Hi @Jilesh980, assigned to you! Happy hacking 🚀

**Comment by EgeAytin** [comment]
Hi @Jilesh980 are there any updates regarding the issue?

**Comment by ThilakReddyy** [comment]
Hello @EgeAytin ,
Can i work on the issue

**Comment by EgeAytin** [comment]
Hi @ThilakReddyy, we've merged this one thanks for the contributions!!
