### ISSUE TITLE
Add Error Codes in documentation

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#873]
**Is your feature request related to a problem? Please describe.**
Here is the available error codes that needed to be added in docs: https://github.com/Permify/permify/blob/master/proto/base/v1/errors.proto

**Describe the solution you'd like**
Error codes can be referenced with the related link (https://github.com/Permify/permify/blob/master/proto/base/v1/errors.proto) in the API overview section: https://docs.permify.co/docs/api-overview/

**Comment by hungaikev** [comment]
Can I pick this issue? A great way for me to get into the code.

**Comment by EgeAytin** [comment]
Of course @hungaikev, assigned this to you. Additional note: If you're interested in getting the latest updates and bounties about our issues, join our Discord channel: https://discord.gg/n6KfzYxhPp.

Happy hacking 🚀
