### ISSUE TITLE
Implement Data Bundles for Memory DB

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#875]
## Description
We need to extend our memory database implementation to support data bundles. This requires the addition of a new table named `bundles` within `internal/storage/memory/migration`. The implementation must be compatible with our `BundleReader`, `BundleWriter`, and `DataWriter` interfaces.

## Current Behavior
Currently, the methods in the `BundleReader` and `BundleWriter` interfaces are not implemented and return a `not implemented` error.

## Expected Behavior
The implementation for the memory database should include:

1. **Reading Data Bundles:**
   - Implement the `Read` method in the `BundleReader` interface to allow retrieval of data bundles based on tenant ID and name.

2. **Writing and Deleting Data Bundles:**
   - Implement the `Write` and `Delete` methods in the `BundleWriter` interface to enable storing and removing data bundles for a tenant.

3. **Running Bundles:**
   - Ensure the implementation is compatible with the `RunBundle` method in the `DataWriter` interface.

## Reference
Use the existing Postgres implementation as a reference for developing the memory DB functionalities.

## Implementation Notes
- The implementation should include the creation of a `bundles` table in `internal/storage/memory/migration`.
- All methods should appropriately handle errors and adhere to the defined interfaces.

## Acceptance Criteria
- [ ] Implementation of the `BundleReader` interface for memory DB.
- [ ] Implementation of the `BundleWriter` interface for memory DB.
- [ ] Ensuring compatibility with the `DataWriter` interface.
- [ ] Comprehensive unit tests for the new functionalities.

**Comment by neo773** [comment]
Hi, I'd like to take a shot at this. could I get assigned?
/attempt #875

**Comment by tolgaOzen** [comment]
Hi @neo773 , it's great to see you here again. I'm assigning this to you. Happy hacking 🚀

**Comment by yuvrajjsingh0** [comment]
Can I get Assigned?
/attempt #875

**Comment by neo773** [comment]
@Rutik7066
Hi there, I’m still working on this and will make a PR soon.

**Comment by Rutik7066** [comment]
Hi @tolgaOzen could please take a look.

**Comment by tolgaOzen** [comment]
I reviewed your PR @Rutik7066, but @neo773 wrote that he worked on it yesterday.

**Comment by Rutik7066** [comment]
Hi @neo773 could please assign this to me. If you haven't completed this one

**Comment by Rutik7066** [comment]
> I reviewed your PR @Rutik7066, but @neo773 wrote that he worked on it yesterday.

Okay it is my first open source contribution so that's why i asked for review.

**Comment by Rutik7066** [comment]
> Wow, this was highly unprofessional even after I confirmed with you that this was a WIP.
> 
> If you really wanted contribute there’s 29+ other open issues you could pick from.
> 
> I just hadn’t had the time yet cuz of my university tests to wrap up this PR.

Getting assigned for the task and not working on it and then telling reasons. Is it professional. Is it not slowly down the progress of this project @tolgaOzen @EgeAytin

**Comment by Rutik7066** [comment]
@tolgaOzen No problem i will delete the PR

**Comment by Rutik7066** [comment]
Hi @tolgaOzen @neo773  i am sorry for my unprofessional behaviour. I desperately need this reward to pay my college fee 400 dollars is big money for me it is 30000+ rupees in our country and with this money i can afford to pay my college fee. Hope you will accept my apology.

**Comment by Rutik7066** [comment]
@neo773 would you please assign this to me

**Comment by tolgaOzen** [comment]
Hello @Rutik7066 , @neo773  has completed half of this task. If you would like to do the 'RunBundle' part, This reward will be split in two. If you accept, I can add you to assignees.

**Comment by Rutik7066** [comment]
I am ready to work with @neo773

**Comment by Rutik7066** [comment]
Started working on runbundle

**Comment by Rutik7066** [comment]
Hey @tolgaOzen. i have implemention of mine PR shall i go with it or @neo773 PR ?

**Comment by tolgaOzen** [comment]
Hello @Rutik7066, it would be better if you do it in @neo773's PR.

**Comment by Rutik7066** [comment]
Hi @tolgaOzen Submitted PR.

**Comment by Rutik7066** [comment]
Hi @tolgaOzen submitted PR with implemention of test.
