### ISSUE TITLE
Permify playground link should be added into navbar

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#88]
"Permify Playground" tab need added to top navigation bar and it should redirect to the [playground](https://play.permify.co/). Specifically, it should be placed as below image pointed.
![Screen Shot 2022-12-19 at 17 28 52](https://user-images.githubusercontent.com/34595361/208448748-e90f1869-1c29-4e4b-8f6d-c607a70e0bdc.png)

**Comment by alielbashir** [comment]
Hello, can I get assigned for this issue?

**Comment by EgeAytin** [comment]
Hi @alielbashir good to see you here [👋](https://emojipedia.org/waving-hand/) I'm assigning you to the issue, happy hacking [🚀](https://emojipedia.org/rocket/)
