### ISSUE TITLE
[BUG] Unable to login to the permify docker container

### ISSUE THREAD

**Issue by nitish-muddhey** [Permify/permify#884]
**Describe the bug**
I am unable to login to the permify container running on my local machine. 
I have tried using the following commands : 
`docker exec -it <container_id> /bin/bash`
`docker exec -it <container_id> /bin/sh`
None of them helped me to login. 

The error message being displayed was : 

```
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
```
So, shell even available in the permify container ?

**Comment by nitish-muddhey** [comment]
@berkeli 
Understood but how do we check if the permify container has bee able to connect to our custom database correctly ? I was thinking of inspecting the container by logging into it and checking if the permify service has correct DB URL set.

**Comment by berkeli** [comment]
@nitish-muddhey you can inspect the container config via the following command:
`docker inspect <container> --format "{{.Config.Env}}`

**Comment by berkeli** [comment]
@nitish-muddhey 
If you really need to login to the container, you can use the following Dockerfile:

```
FROM ubuntu:latest
COPY --from=ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.19 /ko-app/grpc-health-probe /usr/local/bin/grpc_health_probe
COPY --from=ghcr.io/permify/permify /usr/local/bin/permify /usr/local/bin/permify
ENV PATH="$PATH:/usr/local/bin"
ENTRYPOINT ["permify"]
```

**Comment by nitish-muddhey** [comment]
Thanks for sharing dockerfile.
