### ISSUE TITLE
Add JSON Output Option for Logger Configuration

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#929]
**Description:**
There's a need to enhance the logger configuration in the /pkg/cmd/serve.go file to support JSON output. Currently, the logger is set up with a text handler, but it would be beneficial to have an option for JSON output for better integration with log management tools that work more efficiently with JSON.

**Current Implementation:**
```go
// /pkg/cmd/serve.go
logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{
	Level: getLogLevel(cfg.Log.Level),
}))
```

**Proposed Changes:**
1. Modify the Log struct in /pkg/cmd/serve.go to include an Output field, allowing the configuration to specify the desired output format (e.g., text or JSON).

```go
// /pkg/cmd/serve.go
// Log contains configuration for logging.
Log struct {
    Level  string `mapstructure:"level"` // Logging level
    Output string `mapstructure:"output"` // Logging output format, e.g., text, json
}
```

2. Update the logger initialization to use this new Output field to determine whether to use a text handler or a JSON handler.

**Additional Context:**
The addition of a JSON output option will make the logger more versatile and suitable for a variety of logging environments, especially where JSON-formatted logs are preferred for their structured format and ease of parsing.

**Comment by mohanish2504** [comment]
hey @tolgaOzen will like to work on this

**Comment by tolgaOzen** [comment]
Hello @mohanish2504, since @neo773 has opened a PR and requested to claim it, I am assigning this issue to him.

**Comment by berkeli** [comment]
I think it's a bit unprofessional to create a PR without getting the issue assigned. Like @neo773 mentioned some other time there are 200 open issues

**Comment by neo773** [comment]
@berkeli 
I stumbled upon the issue as soon as it was posted but forgot to comment
There's a huge difference in making a PR after someone has been assigned, done work and has literally confirmed with you their still working on it than working on a newly posted issue

Smaller minor issues have always been like this on Algora, guess you haven't seen issues with 5+ people attempting it at the same time 🤷‍♂️

**Comment by berkeli** [comment]
You do you buddy, but please don't insult everyone's intelligence by saying things like "forgot to comment". 

I never compared this issue to the other one, I just said it's unprofessional which it is. 

I've seen issues that algora causes in general, which is why I don't usually bother and happy to contribute any way. My comment was only a remark of this situation, and not a contest of the bounty.

**Comment by neo773** [comment]
> You do you buddy, but please don't insult everyone's intelligence by saying things like "forgot to comment".

My track record of being on top of Algora's leaderboard backs it up I don't have to prove anything.

>I never compared this issue to the other one, I just said it's unprofessional which it is.

You're again making apples to oranges comparison, there's hundreds of bounty hunters on Algora and minor issues like this get solved FAST, My PR after the bounty comment took approximately 12 minutes. 

if it wasn't me probably would've been solved by someone else a couple of minutes later, that's how just the platform works.

Working after getting assigned is mostly for major issues and once people see you've been assigned they respect it and leave it alone.

I'm sorry to say your whole argument of "unprofessionalism" doesn't really apply here.
