### ISSUE TITLE
Guided Tour Interface For Playground

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#933]
## Description
We need to add a tour (https://github.com/gilbarbara/react-joyride) to our playground in order to navigate and welcome the newcomers. 

## Expected Behavior
The tour component for the playground should include 4 steps:

1. Step: **Welcome to the Permify Playground**
   - **Functionality:** The initial step in the tour component should prompt when the playground opens for the first time.
   - **Text:** This environment enables you to create and test your authorization schema within a browser. The Permify playground comprises three main sections: Schema (Authorization Model), Authorization Data, and Enforcement. While we cover these sections in this tour, you can find the complete documentation at [docs.permify.co/ ](https://docs.permify.co/docs/playground/)

2. Step: **Schema (Authorization Model)**
  - **Functionality:** Second step in the tour component should highlight the Schema section in playground.
   - **Text:** You can create your authorization model in this section with using our domain specific language. We already have a couple of use cases and example that you can choose from the dropdown above. Also, you can check our docs to [learn more about how to model authorization](https://docs.permify.co/docs/getting-started/modeling/) in Permify.

3. Step: **Authorization Data**
  - **Functionality:** Third step in the tour component should highlight the Relationships/Attributes below section in playground.
   - **Text:** You can create sample authorization data to test your authorization logic. For instance, to create a relationship between your defined entities, simply click the 'Add Relationship' button. For further information on data creation, please refer to: [documentation link].

4. Step: **Enforcement**
  - **Functionality:** Fourth step in the tour component should highlight the Enforcement section in playground.
   - **Text:** Now that we have sample data and a defined schema, let's perform an access check! The YAML in the Enforcement section represents a test scenario for conducting access checks. To learn more about the capabilities of this YAML, refer to: https://docs.permify.co/docs/playground/#enforcement-access-check-scenarios.

## Implementation Notes
- The tour interface [react-joyride](https://github.com/gilbarbara/react-joyride) should be compatible with the playground's styles and colors. 

## Acceptance Criteria
- [ ] Implement the [react-joyride](https://github.com/gilbarbara/react-joyride) package into Playground.
- [ ] Ensure correct highlighting of the related section in the steps.
- [ ] Confirm compatibility with the current style and colors of the playground.
- [ ] Verify the correctness of the content (text) provided in the issue description.

**Comment by Min2who** [comment]
can i attempt it?

**Comment by EgeAytin** [comment]
Hi @neo773, since you currently have issue you've been working on, I'd like to assign this one to the next available person. I hope you find this fair as well. I'm assigning this issue to @Min2who. Also @Min2who, please comment "/attempt #933" to officially register your attempt, as per the Algora bot. 

Happy hacking 🚀

**Comment by neo773** [comment]
@EgeAytin 
No worries, @Min2who good luck!

**Comment by Min2who** [comment]
@EgeAytin ig it was assigned to me?

**Comment by berkeli** [comment]
> Hi @berkeli could you claim to get the bounty so I can close this issue.
> 
> > 👉 To claim this bounty, submit a pull request that includes the text `/claim #933` somewhere in its body

Not sure why it didn't pick up at first, but has been claimed now. Thank you and this can be closed

**Comment by neo773** [comment]
> > Hi @berkeli could you claim to get the bounty so I can close this issue.
> > > 👉 To claim this bounty, submit a pull request that includes the text `/claim #933` somewhere in its body
> 
> Not sure why it didn't pick up at first, but has been claimed now. Thank you and this can be closed

It was missing a forward slash prefix that's why

**Comment by berkeli** [comment]
> It was missing a forward slash prefix that's why

oh right, I didn't see edit by Tolga so I thought I had put it there. Thanks!
