### ISSUE TITLE
More Meaningful Error Response

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#955]
## Description
This issue suggests an enhancement for the project's error handling mechanism. The current error messages are often too generic or lack detailed information, which makes it difficult for both users and developers to understand the root cause of an issue.

## Example of the Current Issue
- **Where**: [Specify the module or part of the project where the issue occurs]
- **Error Encountered**: [Include the current generic or unhelpful error message]
- **Expected**: A more descriptive error message that could include suggestions for resolution or a reference to where the issue might originate.

## Proposed Solution
Enhancing the error messaging system to provide more context-specific, detailed, and actionable messages would be beneficial. This could involve:
- Adding more detailed descriptions in the error messages.
- Including possible causes or steps to resolve the issue.
- Referencing relevant documentation or resources for troubleshooting.
- **Clear Distinction in Error Codes**: Implementing a clear distinction between 4xx errors, which should indicate client-side issues that should not be retried (e.g., invalid entities/relations not in schema related to request body and schema validation), and 5xx errors for server-side issues that may be temporary and recoverable (e.g., inability to connect to the database, or service health issues).

## Benefits
- **Improved Debugging**: Developers and users can more quickly identify and resolve issues.
- **Better User Experience**: Clearer guidance in case of errors enhances user confidence in the application.
- **Ease of Maintenance**: Maintainers can more easily understand issues reported by users, speeding up the resolution process.
- **Efficient Error Handling**: By categorizing errors more clearly, clients can make informed decisions on whether to retry or handle the error differently.

**Comment by mohanish2504** [comment]
Hey @tolgaOzen can you assign this to me

**Comment by tolgaOzen** [comment]
hello @mohanish2504, I am assigning this to you. Happy hacking 🚀

**Comment by tolgaOzen** [comment]
Hello @mohanish2504, is there any update? We need to prioritize this issue and it should be completed within 2 weeks. If you think it won't be possible to finish in this time, please let me know. Otherwise, I will assign it to myself.

**Comment by mohanish2504** [comment]
Hey @tolgaOzen as I am travelling constanly, I am planning to take this up from next wednesday 17th Jan.
Does that work?

**Comment by mohanish2504** [comment]
Hey @tolgaOzen @EgeAytin I am starting with this now!

**Comment by mohanish2504** [comment]
@tolgaOzen just wanted to ask whether error messages which are interpreted correctly from error code needs detailed messages or not?

Example:
```
ERROR_CODE_NO_ENTITY_REFERENCES_FOUND_IN_SCHEMA = 2024;
ERROR_CODE_INVALID_ARGUMENT = 2025;
```

Looking at it this messages are straight forward. Wanted to know if details need to be sent during this message?
