### ISSUE TITLE
Creating docs sidebar manually

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#98]
Permify using [Docusaurus](https://docusaurus.io/docs) for documentation and currently it generates a sidebar from the docs folder structure. We want to generate sidebar manually with using [sidebar object](https://docusaurus.io/docs/sidebar#sidebar-object).

**Comment by sevkioruc** [comment]
hi @EgeAytin ,
i want to work on it. please assign me :)

**Comment by EgeAytin** [comment]
Done! Happy Hacking @sevkioruc [🚀](https://emojipedia.org/rocket/)
