### ISSUE TITLE
Missing Documentation for Service Section in Configuration File

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#997]
## Description

The `service` section of the configuration file is not documented in the Options section of the Permify documentation. This section is crucial for setting various service-level settings, including circuit breaker usage and cache sizes for schema, permission, and data.

## Details

The missing documentation pertains to the following configuration settings:

- **Circuit Breaker**: Whether to use a circuit breaker.
- **Watch**: Monitoring settings.
- **Schema Cache**: Settings for number of counters and max cost in the schema cache.
- **Permission**: Includes bulk limit, concurrency limit, and cache settings.

## Expected Documentation

It would be helpful if the documentation included examples and explanations for these settings, aiding in better understanding and implementation.

## Reference

The current documentation is available at [Permify Docs](https://docs.permify.co/docs/reference/configuration/).

**Comment by berkeli** [comment]
Hey @tolgaOzen can I work on this?

**Comment by EgeAytin** [comment]
Hi @berkeli, I've closed the PR. Closing this issue too.
